let Lessons=[
    {
        id: 1001,
        subject: "Karate Class",
        location: "Cricklewood Lane, London, NW2 2DQ",
        availablespace: 4,
        image: "Images/karate.jpg",
        description: "Learn self-defense techniques, discipline, and focus through structured martial arts training.",
        price: 230,
        duration: 6,
    },
    {
        id: 1002,
        subject: "Swimming Lessons",
        location: "High Road, Wembley, HA9 7AA",
        availablespace: 2,
        image: "Images/swimming.jpg",
        description: "Master essential swimming skills, from basic strokes to advanced techniques, in a safe and supportive environment.",
        price: 300,
        duration: 3,
    },
    {
        id: 1003,
        subject: "Yoga Classes",
        location: "Market Street, Manchester, M1 1WR",
        availablespace: 9,
        image: "Images/yoga.jpg",
        description: "Improve flexibility, strength, and mindfulness with guided yoga practices tailored for all levels.",
        price: 120,
        duration: 1,
    },
    {
        id: 1004,
        subject: "Dance Classes",
        location: "Green Lane, Birmingham, B9 5BG",
        availablespace: 7,
        image: "Images/dance.jpg",
        description: "Express yourself through movement with fun and engaging lessons in various dance styles like ballet, hip-hop, or salsa.",
        price: 240,
        duration: 2,
    },
    {
        id: 1005,
        subject: "Piano Lessons",
        location: "Camden High Street, London, NW1 8NH",
        availablespace: 19,
        image: "Images/piano.jpg",
        description: "Develop your musical abilities by learning to play classical and modern pieces on the piano.",
        price: 150,
        duration: 6,
    },
    {
        id: 1006,
        subject: "Guitar Lessons",
        location: "Queens Road, Brighton, BN1 3XE",
        availablespace: 11,
        image: "Images/guitar.jpg",
        description: "Pick up the guitar and learn chords, scales, and songs, whether you're a beginner or an aspiring rock star.",
        price: 225,
        duration: 3,
    },
    {
        id: 1007,
        subject: "Cooking Classes",
        location: "Church Street, Sheffield, S1 2GJ",
        availablespace: 10,
        image: "Images/cooking.jpg",
        description: "Explore the art of cooking with hands-on sessions that cover international cuisines and essential techniques.",
        price: 300,
        duration: 2,
    },
    {
        id: 1008,
        subject: "Fitness Bootcamps",
        location: "King Street, Aberdeen, AB24 5AA",
        availablespace: 32,
        image: "Images/fiyness.jpg",
        description: "Push your limits and achieve your fitness goals with high-intensity group workouts.",
        price: 200,
        duration: 1,
    },
    {
        id: 1009,
        subject: "Art Classes",
        location: "St. George's Road, Glasgow, G3 6JA",
        availablespace: 8,
        image: "Images/art.jpg",
        description: "Unleash your creativity with lessons in drawing, painting, or pottery, guided by skilled instructors.",
        price: 350,
        duration: 2,
    },
    {
        id: 1010,
        subject: "Language Classes",
        location: "Victoria Street, Edinburgh, EH1 2JW",
        availablespace: 10,
        image: "Images/language.jpg",
        description: "Learn conversational and written skills in a new language, like French, Spanish, or Japanese, in a fun and immersive setting.",
        price: 225,
        duration: 5,
    },
    {
        id: 1011,
        subject: "Photography Classes",
        location: "Oxford Road, Reading, RG1 7NG",
        availablespace: 4,
        image: "Images/photo.jpg",
        description: "Enhance your photography skills by learning composition, lighting, and editing techniques for stunning shots.",
        price: 100,
        duration: 2,
    },
    {
        id: 1012,
        subject: "Coding Classes",
        location: "Park Road, Luton, LU1 3EU",
        availablespace: 15,
        image: "Images/coding.jpg",
        description: "Dive into the world of programming with beginner-friendly lessons in Python, HTML, and JavaScript.",
        price: 250,
        duration: 3,
    },

]